# Generated by Django 4.2.16 on 2024-11-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
